name: Opencart Test Automation Workflow

on:
  schedule:
  - cron: 30 4 * * *
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Running Opencart Test Automation with Maven
      run: mvn test -Dbrowser=chrome -DisLambdaTest=false -DisHeadless=true
      
    - name: Upload Test logs
      if: always()
      uses: actions/upload-artifact@v4.6.1
      with:
        name: Test Logs
        path: logs/

    - name: Upload Screenshots as Artifacts
      if: always()
      uses: actions/upload-artifact@v4.6.1
      with:
        name: screenshots
        path: screenshots/

    - name: Upload HTML Report as Artifact
      if: always()
      uses: actions/upload-artifact@v4.6.1
      with:
        name: html-report
        path: report.html

    - name: Upload Test Reports
      if: always()
      uses: actions/upload-artifact@v4.6.1
      with:
        name: Test reports
        path: report.html

    - name: Test Execution Status
      run: echo "Test Execution Completed!!"

    - name: Copy Report to gh-pages Folder
      if: always()
      run: |
         mkdir -p public/extent-reports
         mkdir -p public/extent-reports/screenshots

         if [ -f "report.html" ]; then
          cp -R report.html public/extent-reports/
         else
          echo "No report.html found!"
         fi

         if [ -d "screenshots" ]; then
          cp -R screenshots/ public/extent-reports/screenshots/
         else
          echo "No screenshots folder found, skipping copy."
         fi

         ls -l
         
    - name: Deploy
      if: always()
      uses: JamesIves/github-pages-deploy-action@v4.7.3
      with:
        folder: public/extent-reports/
        token: ${{ secrets.SECRET_TOKEN }}
        clean: true

        




      
        
